### ISSUE TITLE
Logs without a stripped version

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#156]
Logs without a stripped log would probably look better if the chopped log used the regular log texture/model if no stripped version exists.
Such as with the crystallized tree from [Blue Skies](https://www.curseforge.com/minecraft/mc-mods/blue-skies), found by growing crystal flowers in the crystal dunes in the Everdawn dimension. It looks quite odd with a stripped oak texture.

![image](https://user-images.githubusercontent.com/12000593/209271425-f33c37cf-abde-4dd8-b01b-873c0fa7729b.png)

**Comment by WenXin20** [comment]
Update - it seems that after the first chop, it then started using the log texture.

**Comment by hammertater** [comment]
Thanks for reporting! The oak texture on the first chop is still concerning, so I’ll get that fixed. Mind if I ask some questions?
- Does it always use the wrong texture for those crystal trees on first chop?
- Does quitting and rejoining the world fix the texture?

**Comment by WenXin20** [comment]
Hi, sorry I just saw this
In the other issue I made, you could see that the bamboo tree also had the same problem. It happened with all of them until I rejoined my world on the server. It could possibly be a server issue.

**Comment by hammertater** [comment]
A handful of texture issues (including #155) should be fixed in 0.17.3, including support for transparent textures. So, the "logs without a stripped version" issue should be fixed, so I'll close this issue. Sometimes after starting the game, the first chop seems to have the wrong texture still, but let's use #157 to track that issue. Thanks for your help, keep the reports coming :)

**Comment by WenXin20** [comment]
Thanks!
