### ISSUE TITLE
Blocks flicker when chopped

### ISSUE THREAD

**Issue by JackiTacki** [hammertater/treechop#168]
During chopping, The internal log tends to flicker before rendering a good split second later. Quite annoying, But simple in nature.

**Comment by hammertater** [comment]
Yeah, it’s tough thing to fix. When you break a block, the client removes it before asking the server if it should, so when the server replies that TreeChop wants to change the block instead of destroy it, the client fixes its mistake. So, the length of the flicker depends mostly on ping. I want to fix this at some point, but it requires some big changes

**Comment by hammertater** [comment]
So, there were two types of flickers people were seeing. With Fabric + Sodium, the flicker would create a brief tear in the world, letting you see through blocks. If that's what you were seeing, it should be fixed in 0.17.6. And if you are using Sodium + Indium, things should look better in general.

The other type of flicker still happens, where the chopped log briefly disappears, but with no world tears. That's much harder to fix, but at least it's a little briefer than the other type of flicker.

**Comment by hammertater** [comment]
Flickering is no more as of treechop 0.18.7
