### ISSUE TITLE
Unnecessarily high FPS impact

### ISSUE THREAD

**Issue by someaddons** [hammertater/treechop#181]
I've noticed that the check to see if the chop item shows up is taking up to 10% of fps, see the profiling below:
![image](https://user-images.githubusercontent.com/38401808/222984011-9968003d-d832-4e1f-b102-3354c08b3d81.png)
https://spark.lucko.me/TizH63iQQn

This was when not looking at a chopable block
I'd suggest to move the code to client tick to limit it to 20times  a second instead of each frame, and maybe skip the check if the looked at block did not change

Forge 1.19.2

**Comment by hammertater** [comment]
Hey, thanks for the profiler output, showed me exactly where the root of the problem was :) There already was a lot of caching with the chop indicator, but a very subtle Forge interaction was causing TreeChop to rebuild its items blacklist every frame. I've posted a new version (0.17.7), should reduce the chop indicator's idle performance impact by about 99.8%.

**Comment by hammertater** [comment]
Hold that thought, 0.17.8 is crashing, will fix tonight

**Comment by hammertater** [comment]
Ok, 0.17.8a is posted. Thanks again for reporting this

**Comment by someaddons** [comment]
thanks for the quick fix :)
