### ISSUE TITLE
Chopping trees no just destroys the block and doesnt drop any logs

### ISSUE THREAD

**Issue by ClarkeIsaac520** [hammertater/treechop#193]
[latest(1).zip](https://github.com/hammertater/treechop/files/11357454/latest.1.zip)

I couldn't upload the the .log file without zipping since it was too big, the tree chopping feature isn't working anymore which might have been caused by the jobs+ lumberjack axe in this modpack. I'm just wondering if theres like a reset on this modpack to reset it or someone that could debug it.

**Comment by hammertater** [comment]
Hey, thanks for reporting, sounds rough. I don't see anything in the log that explains the error. If you're using a specific modpack, could you share a link to it? Or just tell me your mods list

Some more questions:
* Was it working fine, then randomly stopped working?
* Does restarting Minecraft help?
* Are you playing on a server?
* What happens if you turn off chopping? (you can turn it off using the in-game config screen, the default hotkey is `n`)

**Comment by ClarkeIsaac520** [comment]
Ofcourse! Here is the modpack link https://www.curseforge.com/minecraft/modpacks/medieval-mc-new

**Comment by ClarkeIsaac520** [comment]
And yes I am playing on a server it seems to only affect me. When I turn it off I can chop trees down the vanilla way but I still like using the mod so im hoping theres a way I can fix it.

**Comment by ClarkeIsaac520** [comment]
It's back to working, I don't know exactly what fixed it but it hapened after I messed with pressing the keybind for fell tree and then disabling and re enabling the settings in the config

**Comment by hammertater** [comment]
Oh good! Sounds like the server thought you were chopping but your client didn't. Glad it's working 👍
