### ISSUE TITLE
Tropicraft leaves don't break

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#207]
`Minecraft v1.19.2`
`Forge v43.2.7`
[`Tropicraft v9.5.1`](https://www.curseforge.com/minecraft/mc-mods/tropicraft)

Many of Tropicraft leaves blocks, such as Palm Leaves, are not chopped down even though they are included in the `treechop:leaves_like`  tag and `igonore_persistant_leaves = false`. Their leaves don't seem to despawn on their own either.

**Comment by WenXin20** [comment]
Thanks! Also to note, the leaves were directly adjacent to the logs

**Comment by hammertater** [comment]
This should be fixed in 0.18.3, but I haven't tested Tropicraft trees on Minecraft 1.19.2.

Now, if you run into leaves-related issues for other kinds of trees, you might be able to solve them by editing config/treechop.toml, see the section `trees.problematicLeavesTrees` in treechop-common.toml. The `"tropicraft:.*_log(_.*)?"` and `"tropicraft:.*_leaves(_.*)?"` entries tell TreeChop to do more intensive tree detection for Tropicraft logs. I'll add some more documentation for this in the wiki.
