### ISSUE TITLE
TreeChop stopped working

### ISSUE THREAD

**Issue by Jojopet03** [hammertater/treechop#220]
TreeChop stopped working after i fiddled around with some mods. I had some complications but i have the modpack now as it was before. Only thing is, that the Chopping option isnt working anymore, even though i checked the configs and the settings, i wasn`t sneeking,etc.

[latest.log](https://github.com/hammertater/treechop/files/12488970/latest.log)
Im so frustrated bc i don´t wanna loose my World.

**Comment by hammertater** [comment]
Hey, thanks for reporting. Here's a few things you could try:
- Delete the treechop configs (treechop-common.toml and treechop-client.toml)
- Die and respawn
- As a last resort: remove treechop, load the world, save and exit, reinstall treechop. The world should be fine, but you may want to make a backup of it before trying this

I don't see any errors in the log, so I'm guessing the issue here is a desync between the server and player chop settings.

**Comment by hammertater** [comment]
If those suggestions don't work, have you checked if treechop is working in a new world? Could you send me a screenshot of the in-game settings (default key is "n")?

**Comment by Jojopet03** [comment]
Hey, thank you for your answer. Saidly none of your ideas worked and i still have the same problem in a new world.
![Unbenannt](https://github.com/hammertater/treechop/assets/143744958/f64acaa9-5dca-4a36-8e24-54dd77e7cf4b)
![Unbenannt2](https://github.com/hammertater/treechop/assets/143744958/166b49bb-1f38-4024-88ae-a0371bc371f4)

**Comment by hammertater** [comment]
Hmph. Maybe it's a conflict with another mod, or specific mod version. Do you have a log from before, when treechop was working? I might be able to figure out the problem by comparing it with the latest.log you shared

**Comment by Jojopet03** [comment]
Hey, sure, here it is. It was still working then, i think. Were on a vacation in between so I don´t quit remembere.
[2023-07-30-2.log](https://github.com/hammertater/treechop/files/12500169/2023-07-30-2.log)

**Comment by hammertater** [comment]
I take that back - this may be a duplicate of #197. I'll keep this closed and post updates on that issue.
