### ISSUE TITLE
Not working with multi-block mining mods (Industrial Foregoing Tools, Apotheosis, etc)

### ISSUE THREAD

**Issue by Luxaria-source** [hammertater/treechop#237]
Had an issue where this mod would make multi-block mining not work, and for Industrial Foregoing's Infinity Drill it would basically make it to where it displaced all the blocks instead of mining them.

Here's a clip of it happening: https://medal.tv/games/minecraft/clips/1AoqhQkf0elIUJ/d1337CmpfImW?invite=cr-MSxUZlosMTUzODI5Mzc4LA

**Comment by hammertater** [comment]
Thanks for reporting, what version of treechop are you using? There were some brief AOE conflicts in versions 0.18.2 and 0.18.3, I think. The fix was to disable multimine compatibility in the treechop-common.toml config, or to use a different version (treechop 0.18.4 on minecraft 1.19.2, otherwise treechop 0.17.x)

**Comment by jamesbrady226** [comment]
> Thanks for reporting, what version of treechop are you using? There were some brief AOE conflicts in versions 0.18.2 and 0.18.3, I think. The fix was to disable multimine compatibility in the treechop-common.toml config, or to use a different version (treechop 0.18.4 on minecraft 1.19.2, otherwise treechop 0.17.x)

Version was 0.18.2 for 1.20.1

**Comment by hammertater** [comment]
Fixed in 0.18.7, sorry for the wait!
