### ISSUE TITLE
Huge FPS drop when looking at the logs of a giant tree, TPS increase when breaking said logs.

### ISSUE THREAD

**Issue by Infestidos** [hammertater/treechop#244]
Forge 1.19.2 v0.18.4 & v0.18.5. Giant tree (A) vs Regions Unexplored Redwood (B) for spark profiling.

![Trees.](https://github.com/hammertater/treechop/assets/109448821/3ad27489-540c-460a-982c-8b56c221c75d)

Breaking a SINGLE block in creative in the giant tree produces this spark profile: [Tree A](https://spark.lucko.me/ixhLRcjgPG). Breaking an ENTIRE Redwood tree produces this spark profile [Tree B](https://spark.lucko.me/Bwd8SX4yHx). A shows noticeably larger numbers under the mods section.

Simply walking around inside the tree drops my FPS to as low as 3 if I'm looking at logs. The second I look at any other type of block the issue stops. Doesn't matter if I'm looking at the tip of a root, the middle of the tree, or a branch in the canopy.

Both trees using tool tip mods show a max log count of the default ~320. Disabling Chopping or removing this mod fixes the issue.

**Comment by hammertater** [comment]
Thanks for all the info! Treechop’s definitely misbehaving. I’ll get it fixed.

**Comment by hammertater** [comment]
Yikes, some optimization code was actually running _backwards_, so tree detection (checking for leaves connected to the tree) was always giving worst-case performance (scan all the tree's logs) instead of best-case (scan just enough logs to find leaves). Even worse, this step wasn't respecting the max tree size setting. I'll try to get the patch up tonight, it should improve performance significantly.

**Comment by hammertater** [comment]
It should be fixed in 0.18.6

**Comment by Infestidos** [comment]
Thanks that fixed it
