### ISSUE TITLE
Tree chop enable/disable is connected to all my utility keys

### ISSUE THREAD

**Issue by Barerock** [hammertater/treechop#29]
My volume buttons specifically are connected to Tree Chop's enable and disable feature, but are not bound to the feature and aren't able to be unbound. I have NO key bound to the toggle features and my apostrophe key is bound to cycle sneak behavior. Very annoying to change my volume while playing and be forced to pick between my default volume and the amount that lets Tree Chop stay enabled.

Forge 35.1.10 MC 1.16.4 Tree Chop 0.11.1

I'm trying not to update many mods while playing as that can cause issues for servers, that's why my version is out of date.

**Comment by hammertater** [comment]
Hey, sorry about that. This issue will be fixed in the next version (see #27). There's an issue with the way unbound controls are being handled right now, but a quick way to fix it in 0.11.1 is to bind the toggle controls to keys that you won't use, and it should stop your utility keys from triggering them.

I'll update the mod with the fix as soon I get a chance.

**Comment by Barerock** [comment]
Awesome, thanks for the maintenance. Absolutely fantastic mod!

**Comment by hammertater** [comment]
No problem! A new version is posted with the fix (https://www.curseforge.com/minecraft/mc-mods/treechop/files/3153719). I'm gonna go ahead and close this issue. 👍
