### ISSUE TITLE
Prominence 2 problem

### ISSUE THREAD

**Issue by Tweakerer** [hammertater/treechop#295]
So after a while playing in the Prominence 2 modpack, I ran into some problems I thought I could fix but made the it worse. Now I can't chop trees down. Specifically, it doesn't chop the trees down. Instead, after a few chops, the block disappears and leaves the tree floating. It pisses me off and I've tried to revert it back to default but it still doesn't work. Can some PLEASE help me with this?! 

It uses the version 0.18.3, I'm on version 1.20.1 and the fabric is version 0.15.11

PLEASE **_HELP_** ME

**Comment by hammertater** [comment]
It sounds like your "felling" option is disabled. You can re-enable it in treechop's in-game config screen (hotkey is `n` by default):
1. switch to advanced settings (click the two little blocks at the bottom, see screenshot below)
2. enable "felling options"
3. switch back to the basic settings (click the two little blocks again)
4. enable "felling"

Then you'll probably want to switch back to the advanced settings page and hide felling options again, it's only really useful for debugging.

![image](https://github.com/user-attachments/assets/21faf35e-c874-465c-b200-6edb44aa79b7)

If that doesn't help, you could delete `config/treechop-common.toml` and `config/treechop-client.toml` to reset the config files (note that the in-game settings like "felling" are kept server-side, so those still need to be changed in-game). Or download the modpack again and copy their config files, it's possible they made changes there. The most likely reasons for weird behavior caused by config file would be in the mod compatibilities section.

The last thing that can affect treechop behavior is a specific loot table, but I doubt that's the issue here. That's defined in `data/treechop/loot_tables/chopping/chopped_log.json`.

If none of that helps, could you provide screenshots?

**Comment by Tweakerer** [comment]
Thx! I'll try those later when I have the time!

**Comment by Tweakerer** [comment]
Works! I replaced the config files with a new one and it works! I wasn't able to toggle felling since minecraft wasn't letting me but after the replacement, I enabled felling and it works just fine! Tysm!
