### ISSUE TITLE
Suddenly stops functioning

### ISSUE THREAD

**Issue by thedeerirty** [hammertater/treechop#34]
Hey! I'm having a weird issue that came about yesterday
I was using the mod like normal, before my world seemed to lag behind for a bit? and when it resumed I was breaking wood as normal, no cool features. Doubled checked to make sure it was toggled and I wasn't crouching, and making another world didn't fix it. Any clue what could've caused this?

**Comment by thedeerirty** [comment]
Scratch this, sorry. it suddenly has seemed to come back. no clue as to why

**Comment by thedeerirty** [comment]
Well, now its doing it again. Seems to randomly switch off. Does something like terraforge mess up how trees are recognized? It was working on this modded tree just a second ago

**Comment by hammertater** [comment]
Hey, sorry about that. When a player chops, TreeChop disables itself for an instant to keep from crashing due to potential conflicts with other mods. It's supposed to re-enable itself no matter what, but something must be going really, really wrong. Could you send me a recent (server) log, such as `[minecraft folder]/logs/latest.log`?

**Comment by thedeerirty** [comment]
Sure, I can do that here in a second. Some other mods I have probably are conflicted with it, so that's my guess. And don't worry about it! I know sometimes mods can be fuzzy, I understand.

Currently it seems to be working for me with an unmodded axe, but it takes a good bit before it registers that I broke a log with the mods mechanics. I'll get that log!

**Comment by thedeerirty** [comment]
[latest.log](https://github.com/hammertater/treechop/files/5858752/latest.log)

This log is a bit old I think. Might need to restart minecraft to update it it or something. Was made about two hours ago.

**Comment by hammertater** [comment]
Thanks, it should be good, latest.log saved while you play, no need to restart. Did you start seeing a "Woodcutting level up!" message after TreeChop broke?

**Comment by thedeerirty** [comment]
Hm, I think I did, now that you mention it.

**Comment by thedeerirty** [comment]
That's a bummer :/
I wonder if I can figure out a work around or something; thanks for your help.

**Comment by hammertater** [comment]
I think the Project MMO woodcutting message is just a side effect of TreeChop being turned off, I don't think your bug is caused by a conflict with PMMO. The message is handy though because it shows me exactly when the issue started, hehe. I'll make TreeChop give PMMO woodcutting xp in a future update.

I think I have a fix for your issue. I'm still not sure what the root of the issue is, but I'll make it so that TreeChop doesn't stay disabled. It might just be a server lag issue, but if it is a conflict with another mod, that conflict will still be there, so the other mod might bug out a little (let me know if you notice anything weird!). Also, when the conflict does occur, it's possible that TreeChop will be disabled for an instant but should come back on right away.

I'll post a new version with the fix soon-ish.

**Comment by thedeerirty** [comment]
Alright, sweet! I'll let you know if anything else comes up when the new version is dropped! Thanks for the assistance.

**Comment by hammertater** [comment]
No problem! Version 0.12.0 is up. 👍

**Comment by thedeerirty** [comment]
Thanks! I'll install it shortly!
