### ISSUE TITLE
Make "onlyBreakTreesWithLeaves" config default to "true", or add an in-game toggle.

### ISSUE THREAD

**Issue by Enantiomorph** [hammertater/treechop#49]
I understand it was deliberately left as false to keep with the original behavior of the mod (as per the comments in #2), but I think the commonly expected behavior of a tree-cutting mod is to only work on leaved logs by default.

I went to change the setting immediately after trying to deconstruct a wooden structure.

Sneaking or using the toggle keybind lets you work around this while keeping the setting enabled, but perhaps a better solution might be to implement a third state or separate toggle to enable/disable this functionality specifically.

**Comment by hammertater** [comment]
Hey, thanks for posting here!

I definitely don't like the current setup, where you need to restart the game to change some client-side configs. I think I'll take this opportunity to make an in-game interface to handle client-side options. This will also let the mod inform to users when server settings override certain options, like in #50, rather than leaving players confused about why their settings aren't working.

**Comment by hammertater** [comment]
Sorry for the wait! As of 0.14.0, `onlyBreakTreesWithLeaves` has been renamed to `treesMustHaveLeaves` and now defaults to true. I've also added an in-game configuration screen (bound to the `n` key by default) that lets you change this option without restarting. 

It's only for 1.16.3 - 1.16.5 right now, but I'll update the earlier versions eventually
