### ISSUE TITLE
Mod doesn't detect if block is connected to a tree or if the block has leaves around it

### ISSUE THREAD

**Issue by HyperlyBola** [hammertater/treechop#7]
I just made a test that I do with every timber-like mod and built a wall with some planks and no leaves touching it. For some reason the mod turns on even when i'm just chopping a wall. The mod should detect if the block the player is chopping is connected to leaves and/or somehow detect if it's a tree.

**Comment by hammertater** [comment]
Right, I haven't made any attempts yet to distinguish actual trees from everything else. It'll be very simple to add a quick check for leaves to say whether it's a tree or not, so I'll go ahead and add that in the next update and add a config option to disable that behavior (just checking for leaves isn't perfect, I've seen plenty of dead/leafless trees in other mods).

In any case, I think this mod is more forgiving than others when accidentally "chopping" a non-tree block, since everything doesn't break immediately and the chopped block can be removed by sneak-breaking it.

**Comment by hammertater** [comment]
Version 0.11.0 is now available and includes a config option that can be set to only chop if leaves are connected to the tree.

**Comment by hammertater** [comment]
Note that this is a client-side config, so it's located in `config/treechop-client.toml`; set `onlyBreakTreesWithLeaves = true` to get the desired behavior (it is left `false` by default).
