### ISSUE TITLE
NBT contains bad sneak behavior value ""; using default value instead

### ISSUE THREAD

**Issue by Ishinyca** [hammertater/treechop#70]
Coming from MC Eternal v1.4.3.1 modpack. I found this warning report in the server console.

MC Version: 1.12.2
Mod Version: 0.11.4

In the server console, I get this warning of "NBT contains bad sneak bnehavior value ""; using default value instead. This happens when the player joins the server. Screenshot posted below

![unknown](https://user-images.githubusercontent.com/57848555/116950332-ab875180-ac52-11eb-8bee-cbb1f673f3c5.png)

**Comment by hammertater** [comment]
Thanks for reporting this. I quietly fixed it in the 1.16.5 version a while back, but I haven't updated the 1.12.2 version since then. There's a bug in how player "sneak behavior" settings are being saved, so whenever players rejoin a server it'll always revert to "invert chopping". I'll make sure this is fixed in the next update!

**Comment by hammertater** [comment]
This should be fixed as of 0.14.1. Sorry for the wait!
