### ISSUE TITLE
doDaylightCycle false disables chopping

### ISSUE THREAD

**Issue by MaximumFool** [hammertater/treechop#87]
Whenever I set the gamerule doDaylightCycle to false chopping stops working. If I enter a world with it already the rule already false I can chop once before it stops working, and in either case it starts working again when I set doDaylightCycle to true. I'm on 1.12.2 with the MC Eternal modpack and the most up to date version of the mod.

[latest.log](https://github.com/hammertater/treechop/files/7786178/latest.log)

**Comment by hammertater** [comment]
Hey Fool, thanks for reporting this. To fix this, jus turn off treechop's config option for "prevent chop recursion" or something like that. It should be under the "compatibility" section.

The why: there are some mods that cause treechop to descend into an infinite chopping loop, crashing the game. So I made it so that treechop can only chop once per player per server tick. It sounds like, in 1.12.2, the "server tick counter" only advances when the daylight cycle is enabled. I'll try to fix this at some point, but I'm busy with the 1.17/1.18 ports at the moment.

**Comment by hammertater** [comment]
Closing. I don't have much time these days for supporting 1.12, and turning off chop recursion is a good-enough fix.
